#!/usr/bin/env python

#  -*- coding: utf-8 -*-
# Copyright (c) 2015, Mayo Clinic
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this
#     list of conditions and the following disclaimer.
#
#     Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#     Neither the name of the <ORGANIZATION> nor the names of its contributors
#     may be used to endorse or promote products derived from this software
#     without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.


import os
import sys
import rdflib

from dirlistproc import DirectoryListProcessor

import pyjxslt

_parent_dir = os.path.join(os.path.join(os.getcwd(), os.path.dirname(__file__)), '..')
if __name__ == "__main__":
    sys.path.append(_parent_dir)
from hcls_fhir_rdf.rdflib_formats import known_formats, suffix_for
from hcls_fhir_rdf.defaults import *

DEFAULT_LOG_FILE = os.path.basename(__file__) + ".log"


def addargs(parser: argparse.ArgumentParser) -> None:
    """ Add local args to the dirlistproc set
    :param parser: argument parser from dirlistproc
    """
    parser.add_argument("-df", "--definitions",
                        help="Transform definitions file. Default: %s" % DEFAULT_XML_DEFINITIONS)
    parser.add_argument("-of", "--output_format", help="Output file format. Default: 'turtle'",
                        choices=known_formats(), default='turtle')
    parser.add_argument("--gwport", help="XSLT Gateway port", type=int, default=pyjxslt.DEFAULT_PORT)
    add_default_args(parser, __file__)


def procargs(opts: argparse.Namespace) -> None:
    if not opts.indir:
        opts.indir = DEFAULT_EXAMPLE_DIRECTORY
    if not opts.outdir:
        opts.outdir = os.path.join(DEFAULT_TARGET_DIRECTORY, DEFAULT_RDF_DIRECTORY)
    if not opts.definitions:
        opts.definitions = os.path.join(DEFAULT_TARGET_DIRECTORY, DEFAULT_XML_DEFINITIONS)
    opts.flatten = True

    os.makedirs(opts.outdir, exist_ok=True)

    start_logger(opts)
    opts.gw = pyjxslt.Gateway(opts.gwport)
    opts.gw.add_transform('transform', os.path.join(_parent_dir, 'share', 'xsl', 'transform.xsl'))


def proc_input_file(xml_file: str, rdf_file, opts: argparse.Namespace) -> bool:
    """ Convert input_fn into output_fn
    :param xml_file: name of the file to process
    :param rdf_file: (unused)
    :param opts: process options
    :return: True if file was processed, false if it was skipped
    """
    log_info("  Transfoming %s.ttl" % rdf_file, xml_file)
    rdf_file_name = rdf_file + "." + suffix_for(opts.output_format)
    with open(xml_file) as xf:
        xml_input = xf.read()
        rdf = opts.gw.transform('transform', xml_input,
                                fhirdefs=os.path.join(os.path.join(os.getcwd(), opts.definitions)))
        if rdf and not rdf.startswith('ERROR:'):
            with open(rdf_file_name, 'w') as rf:
                rf.write(rdf)
            if 'WARNING: ' in rdf:
                log_warning("Transformation contains warnings!", xml_file)
            else:
                try:
                    rdflib.Graph().parse(rdf_file_name, format=opts.output_format)
                except Exception as e:
                    log_error("Invalid RDF generated!" + str(e), xml_file)
        else:
            log_error(rdf if rdf else "Transformation failed", xml_file)


def main():
    dlp = DirectoryListProcessor(None, "Convert FHIR XML data into RDF", ".xml", '', addargs, procargs)
    nfiles, nsuccess = dlp.run(proc_input_file)
    logging.info("Total files processed=%d Errors=%d" % (nfiles, nfiles - nsuccess))


if __name__ == '__main__':
    main()
